### ISSUE TITLE
Crash Looping in HomeAssistant 2026.1.1

### ISSUE THREAD

**Issue by Jason-Morcos** [tronikos/opower#164]
This is with Seattle City Light (SCL)

I believe this issue was caused by https://github.com/tronikos/opower/pull/163

2026-01-12 09:08:45.151 ERROR (MainThread) [homeassistant.components.opower.coordinator] Unexpected error fetching Opower data
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 416, in _async_refresh
self.data = await self._async_update_data()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/opower/coordinator.py", line 102, in _async_update_data
forecasts: list[Forecast] = await self.api.async_get_forecast()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.13/site-packages/opower/opower.py", line 350, in async_get_forecast
cost_to_date=float(segment.get("soFarUsageCharges", {}).get("value", 0)),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
